repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Git style.
      - id: check-added-large-files # Tags: lint.
        name: Check large files

      - id: check-merge-conflict # Tags: lint.
        name: Check merge conflicts

      - id: check-vcs-permalinks # Tags: lint.
        name: Check VCS permalinks

      - id: forbid-new-submodules # Tags: lint.
        name: Check new submodules

      # Common errors.
      - id: destroyed-symlinks # Tags: lint.
        name: Check destroyed symlinks

      - id: check-executables-have-shebangs # Tags: lint.
        name: Check executables have shebangs

      - id: check-shebang-scripts-are-executable # Tags: lint.
        name: Check shebang scripts are executable

      - id: check-yaml # Tags: lint.
        name: Check YAML files
        args: [--unsafe]

      - id: end-of-file-fixer # Tags: format.
        name: Fix end of files

      - id: fix-byte-order-marker # Tags: format.
        name: Fix byte order markers

      - id: trailing-whitespace # Tags: format.
        name: Fix trailing whitespace
        args: [--markdown-linebreak-ext=md]

      # Cross platform.
      - id: check-case-conflict # Tags: lint.
        name: Check case conflicts

      - id: mixed-line-ending # Tags: format.
        name: Fix mixed line endings
        args: [--fix=lf]

      # Security.
      - id: detect-aws-credentials # Tags: lint.
        name: Detect AWS credentials
        args: [--allow-missing-credentials]

      - id: detect-private-key # Tags: lint.
        name: Detect private keys

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.4.2
    hooks:
      - id: prettier # Tags: format.
        name: Format Markdown files with Prettier
        args: [--prose-wrap=always]
        types: [markdown]

  - repo: https://github.com/google/yamlfmt
    rev: v0.14.0
    hooks:
      - id: yamlfmt # Tags: format.
        name: Format YAML files with yamlfmt

  - repo: local
    hooks:
      - id: ruff-format
        name: Run Ruff formatter
        pass_filenames: false
        require_serial: true
        language: system
        entry: uv run ruff format
        types: [python]

      - id: ruff-fix
        name: Run Ruff checker (fix)
        pass_filenames: false
        require_serial: true
        language: system
        entry: uv run ruff check --fix --fix-only
        types: [python]

      - id: ruff-lint
        name: Run Ruff checker (nofix)
        pass_filenames: false
        require_serial: true
        language: system
        entry: uv run ruff check --no-fix
        types: [python]

      - id: mypy
        name: mypy
        language: system
        entry: uv run dmypy run --timeout 3600 src
        pass_filenames: false
        require_serial: true
        types: [python]
