services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - github-token
        - homebrew-github-api-token

    command: sleep infinity

    environment:
      - GITHUB_TOKEN
      - MISE_GITHUB_TOKEN
      - HOMEBREW_GITHUB_API_TOKEN
      - RENOVATE_GITHUB_COM_TOKEN

      # Hardlinking (which is the default on Linux) not possible
      # as uv cache lives on a different drive in this configuration.
      - UV_LINK_MODE=symlink

    volumes:
      # Workspace itself.
      - workspace:/workspaces/filter-pre-commit-hooks

      # User cache.
      - cache:/home/vscode/.cache

volumes:
  workspace: # Workspace itself.
  cache: # User cache.

secrets:
  github-token:
    environment: GITHUB_TOKEN
  homebrew-github-api-token:
    environment: HOMEBREW_GITHUB_API_TOKEN
