services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      # Hardlinking (which is the default on Linux) not possible
      # as uv cache lives on a different drive in this configuration.
      UV_LINK_MODE: symlink

    command: sleep infinity

    volumes:
      # Workspace itself.
      - ..:/workspace:cached
      # Virtual environment.
      - venv:/workspace/.venv
      # Workspace cache.
      - cache:/workspace/.cache

volumes:
  venv: # Virtual environment.
  cache: # Workspace cache.
