services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Hardlinking (which is the default on Linux) not possible
      # as uv cache lives on a different drive in this configuration.
      UV_LINK_MODE: symlink
    volumes:
      - ..:/workspaces/filter-pre-commit-hooks:cached
      - venv:/workspaces/filter-pre-commit-hooks/.venv
      - pre-commit-cache:/home/vscode/.cache/pre-commit
      - uv-cache:/home/vscode/.cache/uv
    command: sleep infinity
volumes:
  venv:
  pre-commit-cache:
  uv-cache:
