name: Dev Cont

#
# Creates dev container and runs the default just recipe.
#

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/dev-cont.yaml
      - .devcontainer/**
  schedule:
    # At 04:20 on Monday.
    - cron: 20 4 * * 1

defaults:
  run:
    shell: bash

jobs:
  dev-cont:
    name: Dev Cont
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      packages: read
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0

      - name: Set up dev container CLI
        run: npm install -g @devcontainers/cli

      - name: Get dev container CLI version
        run: devcontainer --version

      - name: Create and run dev container
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: devcontainer up --workspace-folder=.

      - name: Check that token is set in dev container
        run: |
          devcontainer exec \
            --workspace-folder=. \
            /usr/bin/env zsh --interactive --login -c \
              "printenv | grep -G -q ^GITHUB_TOKEN="

      - name: Run default just recipe in dev container
        run: |
          devcontainer exec \
            --workspace-folder=. \
            /usr/bin/env zsh --interactive --login -c \
              "just"
